import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import test from "node:test";

test("production output contains the historical globe assets", () => {
  const pageSource = readFileSync("app/page.tsx", "utf8");
  const globeSource = readFileSync("app/components/ExtractionGlobe.tsx", "utf8");
  const cityPageSource = readFileSync("app/cities/[slug]/page.tsx", "utf8");
  const shippingRoutes = JSON.parse(readFileSync("app/data/shipping-routes.generated.json", "utf8"));
  const timelineEventCount = (pageSource.match(/\{ legacyPhase:/g) ?? []).length;
  const timelineDates = [...pageSource.matchAll(/\{ legacyPhase:\s*\d+,\s*date:\s*"([^"]+)"/g)]
    .map((match) => match[1]);
  const phaseMap = globeSource.match(/const TIMELINE_LEGACY_PHASE = \[([\s\S]*?)\] as const;/)?.[1]
    .match(/\d+/g)?.map(Number) ?? [];
  assert.match(pageSource, /historical globe|批判性歷史重構/);
  assert.match(globeSource, /createArcLayer/);
  assert.match(globeSource, /#e7c65a/);
  assert.match(globeSource, /uLiberation/);
  assert.match(globeSource, /aTimelineStart/);
  assert.match(globeSource, /uNetworkIntegrity/);
  assert.match(globeSource, /dynamicCityPulseRings/);
  assert.match(globeSource, /CHINESE_CITY_HISTORIES/);
  assert.match(globeSource, /buildChineseCityLabels/);
  assert.match(globeSource, /uLegacyTimelineStep/);
  assert.match(globeSource, /timelineMode: "event"/);
  assert.equal(timelineEventCount, 57);
  assert.equal(phaseMap.length, timelineEventCount);
  assert.equal(timelineDates[21], "1944.06.15");
  assert.equal(timelineDates[23], "1944.07.09");
  assert.equal(timelineDates[24], "1944.08.01");
  assert.equal(timelineDates[28], "1944.11.24");
  assert.equal(timelineDates[30], "1945.01.16");
  assert.equal(timelineDates[32], "1945.03.09／10");
  assert.equal(timelineDates[38], "1945.08.06 · 08:15");
  assert.equal(timelineDates[39], "1945.08.09 · 11:02");
  assert.match(globeSource, /ALLIED_SURFACE_PATHS/);
  assert.match(globeSource, /networkImmuneFlag/);
  assert.match(globeSource, /geodesicFlag/);
  assert.match(globeSource, /createWartimeLightsLayer/);
  assert.match(globeSource, /createDayNightOverlay/);
  assert.match(globeSource, /createAtomicImpactLayer/);
  assert.match(globeSource, /atomicSkyIllumination/);
  assert.match(globeSource, /atomicRisingClouds/);
  assert.match(globeSource, /focusGlobePoint/);
  assert.match(globeSource, /const ATOMIC_RADIUS_SCALE = 0\.25/);
  assert.match(globeSource, /const ATOMIC_TIME_SCALE = 4 \/ 3/);
  assert.match(globeSource, /aImpactStep/);
  assert.match(globeSource, /route\.strategic \? 8 : 0/);
  assert.match(globeSource, /uEventTimelineStep/);
  assert.match(globeSource, /uSunDirection/);
  assert.match(globeSource, /focusAtlantic/);
  assert.match(globeSource, /CITY_PAGE_PATHS/);
  assert.match(globeSource, /cityPressTimer/);
  assert.match(globeSource, /cityPressTarget/);
  assert.match(globeSource, /camera\.position\.set\(0\.15, 0\.3, 2\.15\)/);
  assert.match(globeSource, /delta \* 0\.0225/);
  assert.match(globeSource, /premultiply\(dragRotation\)/);
  assert.match(globeSource, /EVENT_STEPS\.midway/);
  assert.match(globeSource, /帛琉盟軍反攻/);
  assert.match(globeSource, /臺灣沖航空戰/);
  assert.match(pageSource, /長按 1\.5 秒進入城市頁面/);
  assert.match(globeSource, /\}, 1500\);/);
  assert.match(cityPageSource, /清邁/);
  assert.match(cityPageSource, /滇緬公路/);
  assert.match(cityPageSource, /廣州/);
  assert.match(globeSource, /昆明.*resistance/);
  assert.match(globeSource, /重慶.*resistance/);
  assert.match(globeSource, /拉薩.*resistance/);
  assert.match(globeSource, /dinjan.*kunming/);
  assert.match(globeSource, /ALLIED_AIR_PATHS/);
  assert.match(globeSource, /miami.*borinquen.*atkinson.*belem.*natal.*ascension/s);
  assert.match(globeSource, /sanFrancisco.*honolulu.*christmasIsland.*cantonIsland.*nadi.*noumea/s);
  assert.match(globeSource, /route\.previous/);
  assert.match(globeSource, /const tension = route\.curveStrength \?\?/);
  assert.match(globeSource, /surfaceCubic/);
  assert.match(globeSource, /uSurfaceFollow/);
  assert.match(globeSource, /kind === "sea" \? 72 : 52/);
  assert.match(globeSource, /altitude: 0\.32/);
  assert.match(globeSource, /altitude: 0\.42/);
  assert.match(globeSource, /昭南（新加坡）/);
  assert.match(globeSource, /AIRFIELD_POINTS\.bandung/);
  assert.match(globeSource, /AIRFIELD_POINTS\.mandalay/);
  assert.match(globeSource, /OPERATION_POINTS\.pearlHarbor/);
  assert.match(globeSource, /OPERATION_POINTS\.midway/);
  assert.match(globeSource, /OPERATION_POINTS\.darwin/);
  assert.match(globeSource, /PORTS\.qingdao/);
  assert.match(globeSource, /generatedShippingLanes/);
  assert.equal(shippingRoutes.length, 35);
  assert.ok(shippingRoutes.every((lane) => lane.path.length > 1));
  assert.ok(shippingRoutes.every((lane) => lane.smooth.length === lane.path.length - 1));
  assert.ok(shippingRoutes.some((lane) => lane.smooth.includes(false)));
  assert.match(pageSource, /佔領時間線/);
  assert.match(pageSource, /1945\.09\.02/);
  assert.match(pageSource, /1941\.10\.04/);
  assert.match(pageSource, /1941\.10\.31/);
  assert.match(pageSource, /1944\.04\.22/);
  assert.match(pageSource, /1945\.05\.26/);
  assert.match(pageSource, /1945\.06\.29/);
  assert.match(pageSource, /1945\.07\.28/);
  assert.match(pageSource, /1945\.08\.30/);
  assert.match(pageSource, /1945\.10\.25/);
  assert.match(pageSource, /1945\.12\.27/);
  assert.match(pageSource, /1941\.12\.07／08/);
  assert.match(pageSource, /1942\.02\.19/);
  assert.match(pageSource, /1942\.06\.04/);
  assert.match(pageSource, /帛琉盟軍反攻／臺灣沖航空戰／重返菲律賓/);
  assert.match(pageSource, /1943\.12/);
  assert.match(pageSource, /1944\.02\.17／18/);
  assert.match(pageSource, /1944\.06\.15/);
  assert.match(pageSource, /1944\.07\.09/);
  assert.match(pageSource, /1944\.08\.01/);
  assert.match(pageSource, /B-29由塞班首次空襲東京/);
  assert.match(pageSource, /1945\.01\.16/);
  assert.match(pageSource, /1945\.03\.09／10/);
  assert.match(pageSource, /1945\.03\.27/);
  assert.match(pageSource, /1945\.08\.06 · 08:15/);
  assert.match(pageSource, /1945\.08\.09 · 11:02/);
  assert.match(pageSource, /播放原爆雙節點/);
  assert.match(pageSource, /原爆記錄/);
  assert.match(pageSource, /const ATOMIC_HOLD_MS = Math\.round\(5200 \* 4 \/ 3\)/);
  assert.match(pageSource, /setTimelinePlaying\(true\)/);
  assert.match(pageSource, /不作勝利式呈現/);
  assert.match(pageSource, /滇緬公路中斷／駝峰接續/);
  assert.match(pageSource, /中印公路重開/);
  assert.match(pageSource, /租借援華：深海藍海運／陸運/);
  assert.match(pageSource, /盟軍航空：運量控制粗細／亮度/);
  assert.match(pageSource, /貼海大弧：史料海運走廊/);
  assert.match(pageSource, /完整貼海弧：盟軍跨洋援華海運/);
  assert.match(pageSource, /觀察大西洋/);
  assert.match(pageSource, /強化晨昏線 · 1942戰時燈火/);
  assert.match(pageSource, /桂林、柳州失守/);
  assert.match(pageSource, /未被佔領與收復後為藍色，日軍佔領期間為紅色/);
  assert.match(pageSource, /不在8月15日一刀切換色/);
  assert.match(globeSource, /occupied: \[\[2, 2\], \[19, 50\]\]/);
  assert.match(globeSource, /occupied: \[\[29, 34\]\]/);
  assert.match(globeSource, /label: "香港"[\s\S]*?occupied: \[\[6, 42\]\]/);
  assert.match(globeSource, /label: "臺北"[\s\S]*?occupied: \[\[0, 54\]\]/);
  assert.match(pageSource, /交通網/);
  assert.match(pageSource, /自動循環/);
  assert.match(pageSource, /盟軍空運/);
  assert.match(pageSource, /運量控制粗細／亮度/);
  assert.match(globeSource, /ALLIED_AIR_VOLUME_BY_STEP/);
  assert.match(globeSource, /uAlliedVolume/);
  assert.match(globeSource, /curveStrength: 0\.36/);
  assert.match(globeSource, /\[-36\.8, 20\]/);
  assert.match(globeSource, /\[-25, 51\]/);
  assert.equal(existsSync("dist/client/1935-air-map-reference.jpg"), true);
  assert.equal(existsSync("dist/client/1941-map-reference.jpg"), true);
  assert.equal(existsSync("dist/client/occupation-timeline-4k.png"), true);
  assert.equal(existsSync("dist/client/og.png"), true);
  assert.doesNotMatch(pageSource, /codex-preview|SkeletonPreview/);
});
